import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopNavigation from "./components/desktopnav";
import SideBar from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="flex flex-row">
        <SideBar />
        <DesktopNavigation /> 
      </div>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="ml-[5%] mt-[2%]">
          {children}
        </div>
      </body>
    </html>
  );
}
